//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pm_pr_3_AKi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int id_Tovara { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] image { get; set; }
    }
}
